export const SET_LIMIT = 100;
export const WORDS_LIMIT = 100;
export const MIN_WORDS_COUNT = 4;
export const MINUTES_FOR_STUDY_ONE_WORD = 3;
export const MAX_MEGABYTES_PER_FILE = 5;
export const MAX_FILE_SIZE = MAX_MEGABYTES_PER_FILE * 1024 * 1024;
export const ALLOWED_FILE_TYPES = ["image/jpeg", "image/png", "image/jpg", "image/webp", "image/gif"];

export const AI_GENERATED_STORIES_ALLOWED_COUNT_FOR_DEFAULT_USER = 5;
export const AI_GENERATED_STORIES_ALLOWED_COUNT_FOR_PREMIUM_USER = 30;

export const AI_GENERATED_WORDS_ALLOWED_COUNT_FOR_DEFAULT_USER = 5;
export const AI_GENERATED_WORDS_ALLOWED_COUNT_FOR_PREMIUM_USER = 30;

export const AI_GENERATED_IMAGES_ALLOWED_COUNT_FOR_DEFAULT_USER = 5;
export const AI_GENERATED_IMAGES_ALLOWED_COUNT_FOR_PREMIUM_USER = 30;
